server:
  port: 8083
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/shop_bd?serverTimezone=GMT%2B8
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver


    # qq mail
  mail:
    host: smtp.qq.com
    username: 2071252817@qq.com
    password: hkepdssgmeppehaj
    default-encoding: utf-8
    port: 587
    properties:
        mail.smtp.auth: true
        mail.smtp.connectiontimeout: 5000
        mail.smtp.timeout: 5000
        mail.smtp.writetimeout: 5000
        mail.smtp.starttls.enabl: true


# 配置mybatis 引入·mybatis-plus则失效
mybatis-plus:
###  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:/mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









